// Decide whether an automatic trigger may spend one bounded edition attempt.
import fs from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import newsDay from './lib/news-day.cjs';
import attemptsContract from './lib/edition-attempts.cjs';

export function publicationPlan({ event, date, attempts, slot = 'morning', retry = false }) {
  if (!['morning', 'noon'].includes(slot)) throw new Error('Invalid publication slot');
  if (event === 'workflow_dispatch') return { run: true, slot, retry };
  const rows = attemptsContract.readAttempts(attempts).attempts.filter(row => row.editorialDate === date);
  // A successful artifact or pending review is never regenerated by a code check.
  if (rows.some(row => ['published', 'review-required'].includes(row.state))) return { run: false, slot, retry: false };
  const failed = rows.filter(row => row.state === 'failed')
    .sort((a, b) => Number(b.slot === 'noon') - Number(a.slot === 'noon'))[0];
  if (failed) {
    if ((failed.recoveries || []).length >= attemptsContract.MAX_RECOVERY_RUNS) throw new Error(`Bounded recovery exhausted: ${date}/${failed.slot}`);
    return { run: true, slot: failed.slot, retry: true };
  }
  if (rows.some(row => row.state === 'started')) throw new Error(`Incomplete edition attempt requires diagnosis: ${date}`);
  // A successful code check can recover a failure, never start unsolicited generation.
  return { run: event === 'schedule', slot, retry: false };
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const data = new URL('../data/edition-attempts.json', import.meta.url);
  const plan = publicationPlan({
    event: process.env.TRIGGER_EVENT, date: newsDay.editorialDay(new Date()),
    attempts: JSON.parse(fs.readFileSync(data, 'utf8')),
    slot: process.env.REQUESTED_SLOT || 'morning', retry: process.env.REQUESTED_RECOVERY === 'true',
  });
  const output = `run=${plan.run}\nslot=${plan.slot}\nretry=${plan.retry ? '1' : '0'}\n`;
  process.stdout.write(output);
  if (process.env.GITHUB_OUTPUT) fs.appendFileSync(process.env.GITHUB_OUTPUT, output);
}
