// Decide whether an automatic trigger may spend one bounded edition attempt.
import fs from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import newsDay from './lib/news-day.cjs';
import attemptsContract from './lib/edition-attempts.cjs';

export function publicationPlan({ event, date, attempts, slot = 'morning', retry = false, edition }) {
  if (!['morning', 'noon'].includes(slot)) throw new Error('Invalid publication slot');
  const rows = attemptsContract.readAttempts(attempts).attempts.filter(row => row.editorialDate === date);
  // A successful artifact or pending review is never regenerated by a code check.
  const publishedRows = rows.filter(row => row.state === 'published');
  const published = publishedRows.find(row => row.artifactHash === edition?.artifactHash) || publishedRows[0];
  if (published) {
    if (edition?.editorialDate !== date || edition?.artifactHash !== published.artifactHash) {
      throw new Error(`Published ledger does not match the committed public artifact: ${date}`);
    }
    return { run: false, slot: published.slot, retry: false, verify: true };
  }
  if (rows.some(row => row.state === 'review-required')) return { run: false, slot, retry: false };
  if (event === 'workflow_dispatch') return { run: true, slot, retry };
  const failed = rows.filter(row => row.state === 'failed')
    .sort((a, b) => Number(b.slot === 'noon') - Number(a.slot === 'noon'))[0];
  if (failed) {
    if ((failed.recoveries || []).length >= attemptsContract.MAX_RECOVERY_RUNS) {
      // The separate noon attempt is already part of the daily budget contract.
      // Once morning recovery is exhausted, it is the only remaining bounded path.
      if (failed.slot === 'morning' && !rows.some(row => row.slot === 'noon')) {
        return { run: true, slot: 'noon', retry: false };
      }
      throw new Error(`Bounded recovery exhausted: ${date}/${failed.slot}`);
    }
    return { run: true, slot: failed.slot, retry: true };
  }
  if (rows.some(row => row.state === 'started')) throw new Error(`Incomplete edition attempt requires diagnosis: ${date}`);
  // A successful code check can recover a failure, never start unsolicited generation.
  return { run: event === 'schedule', slot, retry: false };
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const data = new URL('../data/edition-attempts.json', import.meta.url);
  const edition = JSON.parse(fs.readFileSync(new URL('../data/edition.json', import.meta.url), 'utf8'));
  const plan = publicationPlan({
    edition,
    event: process.env.TRIGGER_EVENT, date: newsDay.editorialDay(new Date()),
    attempts: JSON.parse(fs.readFileSync(data, 'utf8')),
    slot: process.env.REQUESTED_SLOT || 'morning', retry: process.env.REQUESTED_RECOVERY === 'true',
  });
  const output = `run=${plan.run}\nslot=${plan.slot}\nretry=${plan.retry ? '1' : '0'}\nverify=${Boolean(plan.verify)}\neditorial_date=${edition.editorialDate}\nartifact_hash=${edition.artifactHash}\n`;
  process.stdout.write(output);
  if (process.env.GITHUB_OUTPUT) fs.appendFileSync(process.env.GITHUB_OUTPUT, output);
}
