// Decide whether an automatic trigger may spend one bounded edition attempt.
import fs from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import newsDay from './lib/news-day.cjs';
import attemptsContract from './lib/edition-attempts.cjs';

// Shared workflow concurrency guarantees the previous production runner has exited.
// Only the new durable protocol proves its unknown bill is already accounted for;
// legacy incomplete attempts still require diagnosis rather than a guessed refund.
export function recoverInterruptedAttempts(attempts, date, runId, runAttempt = '1') {
  if (!runId) throw new Error('Interrupted-attempt recovery requires the current workflow run');
  for (const row of attemptsContract.readAttempts(attempts).attempts) {
    if (row.editorialDate !== date || row.state !== 'started') continue;
    const accounting = row.modelAccounting;
    if (accounting?.version !== 1 || !/^\d+$/.test(accounting.runId || '')
      || (accounting.runId === String(runId) && String(accounting.runAttempt || '1') === String(runAttempt)) || !accounting.receipts?.length
      || accounting.receipts.some(receipt => !Number.isFinite(receipt.accountedUSD) || receipt.accountedUSD < 0)
      || Number(row.costUSD) + 0.000001 < accounting.receipts.reduce((sum, receipt) => sum + receipt.accountedUSD, 0)) continue;
    row.state = 'failed';
    row.reason = 'Previous runner interrupted; maximum charges retained for unsettled model calls';
    row.completedAt = new Date().toISOString();
  }
  return attempts;
}

export function publicationPlan({ event, date, attempts, slot = 'morning', retry = false, edition }) {
  if (!['morning', 'noon'].includes(slot)) throw new Error('Invalid publication slot');
  const rows = attemptsContract.readAttempts(attempts).attempts.filter(row => row.editorialDate === date);
  // A successful artifact or pending review is never regenerated by a code check.
  const publishedRows = rows.filter(row => row.state === 'published');
  const published = publishedRows.find(row => row.artifactHash === edition?.artifactHash) || publishedRows[0];
  if (published) {
    if (edition?.editorialDate !== date || edition?.artifactHash !== published.artifactHash) {
      throw new Error(`Published ledger does not match the committed public artifact: ${date}`);
    }
    return { run: false, slot: published.slot, retry: false, verify: true };
  }
  if (rows.some(row => row.state === 'review-required')) return { run: false, slot, retry: false };
  if (event === 'workflow_dispatch') return { run: true, slot, retry };
  const failed = rows.filter(row => row.state === 'failed')
    .sort((a, b) => Number(b.slot === 'noon') - Number(a.slot === 'noon'))[0];
  if (failed) {
    if ((failed.recoveries || []).length >= attemptsContract.MAX_RECOVERY_RUNS) {
      // The separate noon attempt is already part of the daily budget contract.
      // Once morning recovery is exhausted, it is the only remaining bounded path.
      if (failed.slot === 'morning' && !rows.some(row => row.slot === 'noon')) {
        return { run: true, slot: 'noon', retry: false };
      }
      throw new Error(`Bounded recovery exhausted: ${date}/${failed.slot}`);
    }
    return { run: true, slot: failed.slot, retry: true };
  }
  if (rows.some(row => row.state === 'started')) throw new Error(`Incomplete edition attempt requires diagnosis: ${date}`);
  // A successful code check can recover a failure, never start unsolicited generation.
  return { run: event === 'schedule', slot, retry: false };
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const data = new URL('../data/edition-attempts.json', import.meta.url);
  const edition = JSON.parse(fs.readFileSync(new URL('../data/edition.json', import.meta.url), 'utf8'));
  const date = newsDay.editorialDay(new Date());
  let attempts = attemptsContract.readAccountingAttempts(JSON.parse(fs.readFileSync(data, 'utf8')));
  if (process.env.GITHUB_ACTIONS === 'true') {
    attempts = recoverInterruptedAttempts(attempts, date, process.env.GITHUB_RUN_ID, process.env.GITHUB_RUN_ATTEMPT);
    fs.writeFileSync(data, `${JSON.stringify(attempts, null, 2)}\n`);
  }
  const plan = publicationPlan({
    edition,
    event: process.env.TRIGGER_EVENT, date, attempts,
    slot: process.env.REQUESTED_SLOT || 'morning', retry: process.env.REQUESTED_RECOVERY === 'true',
  });
  const output = `run=${plan.run}\nslot=${plan.slot}\nretry=${plan.retry ? '1' : '0'}\nverify=${Boolean(plan.verify)}\neditorial_date=${edition.editorialDate}\nartifact_hash=${edition.artifactHash}\n`;
  process.stdout.write(output);
  if (process.env.GITHUB_OUTPUT) fs.appendFileSync(process.env.GITHUB_OUTPUT, output);
}
